version: "3"

services:

  postgres:
    container_name: postgres_container
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - aol
    restart: unless-stopped

  app:
    container_name: student_service_container
    image: student_service_image
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=changeme
      - DB_NAME=student-service
      - DB_OPTIONS=sslmode=disable
      - OTEL_BASE_URL=collector:4317
      - APP_PORT=8001
    ports:
      - "8001:8001"
    networks:
      - aol
    depends_on:
      - postgres

networks:
  aol:
    driver: bridge

volumes:
  postgres:

